apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep3
spec:
  replicas: 6
  strategy:
#   type: Recreate
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  selector:
    matchLabels:
      a: b
  template:
    metadata:
      labels:
        a: b
    spec:
      containers:
        - name: web
          image: httpd
